export type Theme = 'system' | 'light' | 'dark'
export type Contrast = 'system' | 'default' | 'medium' | 'high'
export type ReducedMotion = 'system' | 'reduced' | 'unreduced'
export type ReducedTransparency = 'system' | 'reduced' | 'unreduced'

export type IconStyle
  = | 'Material Symbols Outlined'
    | 'Material Symbols Rounded'
    | 'Material Symbols Sharp'
export type MotionScheme = 'standard' | 'expressive'
export type Color
  = | 'primary'
    | 'on-primary'
    | 'primary-container'
    | 'on-primary-container'
    | 'secondary'
    | 'on-secondary'
    | 'secondary-container'
    | 'on-secondary-container'
    | 'tertiary'
    | 'on-tertiary'
    | 'tertiary-container'
    | 'on-tertiary-container'
    | 'error'
    | 'on-error'
    | 'error-container'
    | 'on-error-container'
    | 'surface'
    | 'on-surface'
    | 'surface-variant'
    | 'on-surface-variant'
    | 'surface-container-highest'
    | 'surface-container-high'
    | 'surface-container'
    | 'surface-container-low'
    | 'surface-container-lowest'
    | 'inverse-surface'
    | 'inverse-on-surface'
    | 'outline'
    | 'outline-variant'
    | 'primary-fixed'
    | 'on-primary-fixed'
    | 'primary-fixed-dim'
    | 'on-primary-fixed-variant'
    | 'inverse-primary'
    | 'secondary-fixed'
    | 'on-secondary-fixed'
    | 'secondary-fixed-dim'
    | 'on-secondary-fixed-variant'
    | 'tertiary-fixed'
    | 'on-tertiary-fixed'
    | 'tertiary-fixed-dim'
    | 'on-tertiary-fixed-variant'
    | 'surface-bright'
    | 'surface-dim'
    | 'scrim'
    | 'shadow'
