export type Theme = 'light' | 'dark' | 'system';
export type Contrast = 'system' | 'default' | 'medium' | 'high';
export type MotionScheme = 'standard' | 'expressive';
export type ColorTokens = {
  'primary': string;
  'on-primary': string;
  'primary-container': string;
  'on-primary-container': string;
  'secondary': string;
  'on-secondary': string;
  'secondary-container': string;
  'on-secondary-container': string;
  'tertiary': string;
  'on-tertiary': string;
  'tertiary-container': string;
  'on-tertiary-container': string;
  'error': string;
  'on-error': string;
  'error-container': string;
  'on-error-container': string;
  'surface': string;
  'on-surface': string;
  'surface-variant': string;
  'on-surface-variant': string;
  'surface-container-highest': string;
  'surface-container-high': string;
  'surface-container': string;
  'surface-container-low': string;
  'surface-container-lowest': string;
  'inverse-surface': string;
  'inverse-on-surface': string;
  'outline': string;
  'outline-variant': string;
  'primary-fixed': string;
  'on-primary-fixed': string;
  'primary-fixed-dim': string;
  'on-primary-fixed-variant': string;
  'inverse-primary': string;
  'secondary-fixed': string;
  'on-secondary-fixed': string;
  'secondary-fixed-dim': string;
  'on-secondary-fixed-variant': string;
  'tertiary-fixed': string;
  'on-tertiary-fixed': string;
  'tertiary-fixed-dim': string;
  'on-tertiary-fixed-variant': string;
  'surface-bright': string;
  'surface-dim': string;
  'scrim': string;
  'shadow': string;
};
