export type MotionSchemeValue = 'standard' | 'expressive'
export type MotionDuration = 'fast' | 'default' | 'slow'
export type MotionTarget = 'spatial' | 'effects'
export type YuIconStyleValue = 'outlined' | 'rounded' | 'sharp'
export type YuButtonTypeValue = 'default' | 'toggle'
export type YuButtonSizeValue = 'small' | 'xsmall' | 'medium' | 'large' | 'xlarge'
export type YuButtonShapeValue = 'round' | 'square'
export type YuButtonColorValue = 'elevated' | 'filled' | 'tonal' | 'outlined' | 'standard'

export type MdSysColorName
  = | 'primary'
    | 'on-primary'
    | 'primary-container'
    | 'on-primary-container'
    | 'secondary'
    | 'on-secondary'
    | 'secondary-container'
    | 'on-secondary-container'
    | 'tertiary'
    | 'on-tertiary'
    | 'tertiary-container'
    | 'on-tertiary-container'
    | 'error'
    | 'on-error'
    | 'error-container'
    | 'on-error-container'
    | 'surface'
    | 'on-surface'
    | 'surface-variant'
    | 'on-surface-variant'
    | 'surface-container-highest'
    | 'surface-container-high'
    | 'surface-container'
    | 'surface-container-low'
    | 'surface-container-lowest'
    | 'inverse-surface'
    | 'inverse-on-surface'
    | 'outline'
    | 'outline-variant'
    | 'primary-fixed'
    | 'on-primary-fixed'
    | 'primary-fixed-dim'
    | 'on-primary-fixed-variant'
    | 'inverse-primary'
    | 'secondary-fixed'
    | 'on-secondary-fixed'
    | 'secondary-fixed-dim'
    | 'on-secondary-fixed-variant'
    | 'tertiary-fixed'
    | 'on-tertiary-fixed'
    | 'tertiary-fixed-dim'
    | 'on-tertiary-fixed-variant'
    | 'surface-bright'
    | 'surface-dim'
    | 'scrim'
    | 'shadow'
export type MdSysColor = `md.sys.color.${MdSysColorName}`
