import type { ModuleOptions, DeepRequired } from './module'

export const defaultOptions = {
  fonts: true,
  image: true,
  theme: 'system',
  contrast: 'system',
  motionScheme: 'expressive',
  iconStyle: 'Material Symbols Outlined',
  references: {
    color: {
      sourceColor: '#6750a4',
    },
    typography: {
      typefaces: {
        brand: ['sans-serif'],
        plain: ['sans-serif'],
      },
      weights: {
        regular: 400,
        medium: 500,
        bold: 700,
      },
    },
  },
  elevationSets: [
    {
      name: 'level5',
      identifier: '037aa428-d531-4429-93e9-1a8eeaf05019',
      length: [
        [0, 7, 8, -4],
        [0, 12, 17, 2],
        [0, 5, 22, 4],
      ],
    },
    {
      name: 'level4',
      identifier: '2f677656-3c56-4baf-9f56-2a1b8ae3f03c',
      length: [
        [0, 5, 5, -3],
        [0, 8, 10, 1],
        [0, 3, 14, 2],
      ],
    },
    {
      name: 'level3',
      identifier: '468d8c15-eeec-41b1-8341-dacb213f6ca3',
      length: [
        [0, 3, 5, -1],
        [0, 6, 10, 0],
        [0, 1, 18, 0],
      ],
    },
    {
      name: 'level2',
      identifier: '273961cb-cbab-41b1-bc98-cef1ea328da4',
      length: [
        [0, 3, 3, -2],
        [0, 3, 4, 0],
        [0, 1, 8, 0],
      ],
    },
    {
      name: 'level1',
      identifier: 'f2a72dde-936d-4124-bf1a-f3c6aa74eb5b',
      length: [
        [0, 2, 1, -1],
        [0, 1, 1, 0],
        [0, 1, 3, 0],
      ],
    },
    {
      name: 'level0',
      identifier: '06fbbfac-4703-49d2-acd8-035a9b0142e3',
      length: [
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
      ],
    },
  ],
  cornerSets: [
    {
      name: 'none',
      identifier: '81d89965-7e96-4fa1-a8d9-bc1d5fe2ad8a',
      value: 0,
    },
    {
      name: 'extra-small',
      identifier: '52feac0e-e26c-4c6f-bc0f-d8460a094ff1',
      value: 4,
    },
    {
      name: 'small',
      identifier: 'e257d01b-b106-4d22-85cd-0d41d404456e',
      value: 8,
    },
    {
      name: 'medium',
      identifier: 'dc325370-0f7b-48d8-93b0-78a5b8ebaff6',
      value: 12,
    },
    {
      name: 'large',
      identifier: '5221c128-a2d5-47ee-9eeb-9af756728e69',
      value: 16,
    },
    {
      name: 'large-increased',
      identifier: '9aa337a0-102e-4f31-a605-f4a0f052ad76',
      value: 20,
    },
    {
      name: 'extra-large',
      identifier: '33de19d3-134b-44ba-ad0e-7ad69695c755',
      value: 28,
    },
    {
      name: 'extra-large-increased',
      identifier: '6e6a8585-09c8-414a-afd0-0531d424d18b',
      value: 32,
    },
    {
      name: 'extra-extra-large',
      identifier: 'a5718a67-e5df-4084-8aef-6f12bc35a2e6',
      value: 48,
    },
  ],
  motionSets: [
    {
      name: 'expressive',
      identifier: 'f6d1fea2-a6c8-4ca5-9086-399b501321ff',
      spatial: {
        fast: {
          duration: 350,
          timingFunction: [0.42, 1.67, 0.21, 0.90],
        },
        default: {
          duration: 500,
          timingFunction: [0.38, 1.21, 0.22, 1.00],
        },
        slow: {
          duration: 650,
          timingFunction: [0.39, 1.29, 0.35, 0.98],
        },
      },
      effects: {
        fast: {
          duration: 150,
          timingFunction: [0.31, 0.94, 0.34, 1.00],
        },
        default: {
          duration: 200,
          timingFunction: [0.34, 0.80, 0.34, 1.00],
        },
        slow: {
          duration: 300,
          timingFunction: [0.34, 0.88, 0.34, 1.00],
        },
      },
    },
    {
      name: 'standard',
      identifier: '57dba8bc-0299-4f14-849c-fb5577058968',
      spatial: {
        fast: {
          duration: 350,
          timingFunction: [0.27, 1.06, 0.18, 1.00],
        },
        default: {
          duration: 500,
          timingFunction: [0.27, 1.06, 0.18, 1.00],
        },
        slow: {
          duration: 750,
          timingFunction: [0.27, 1.06, 0.18, 1.00],
        },
      },
      effects: {
        fast: {
          duration: 150,
          timingFunction: [0.31, 0.94, 0.34, 1.00],
        },
        default: {
          duration: 200,
          timingFunction: [0.34, 0.80, 0.34, 1.00],
        },
        slow: {
          duration: 300,
          timingFunction: [0.34, 0.88, 0.34, 1.00],
        },
      },
    },
  ],
  typescaleSets: [
    {
      name: 'baseline',
      identifier: 'dd69f84a-8858-4aa7-9f24-f9095dae3378',
      display: {
        large: {
          font: 'brand',
          weight: 'regular',
          size: 57,
          tracking: 0,
          lineHeight: 64,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 57 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'brand',
          weight: 'regular',
          size: 45,
          tracking: 0,
          lineHeight: 52,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 45 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'brand',
          weight: 'regular',
          size: 36,
          tracking: 0,
          lineHeight: 44,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 36 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      headline: {
        large: {
          font: 'brand',
          weight: 'regular',
          size: 32,
          tracking: 0,
          lineHeight: 40,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 32 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'brand',
          weight: 'regular',
          size: 28,
          tracking: 0,
          lineHeight: 36,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 28 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'brand',
          weight: 'regular',
          size: 24,
          tracking: 0,
          lineHeight: 32,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 24 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      title: {
        large: {
          font: 'brand',
          weight: 'regular',
          size: 22,
          tracking: 0,
          lineHeight: 28,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 22 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'plain',
          weight: 'medium',
          size: 16,
          tracking: 0,
          lineHeight: 24,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 16 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'plain',
          weight: 'medium',
          size: 14,
          tracking: 0,
          lineHeight: 20,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 14 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      body: {
        large: {
          font: 'plain',
          weight: 'regular',
          size: 16,
          tracking: 0,
          lineHeight: 24,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 16 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'plain',
          weight: 'regular',
          size: 14,
          tracking: 0,
          lineHeight: 20,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 14 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'plain',
          weight: 'regular',
          size: 12,
          tracking: 0.1,
          lineHeight: 16,
          axes: [
            { name: 'wght', value: 400 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 12 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      label: {
        large: {
          font: 'plain',
          weight: 'medium',
          size: 14,
          tracking: 0,
          lineHeight: 20,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 14 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'plain',
          weight: 'medium',
          size: 12,
          tracking: 0.1,
          lineHeight: 16,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 12 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'plain',
          weight: 'medium',
          size: 11,
          tracking: 0.1,
          lineHeight: 16,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 11 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
    },
    {
      name: 'emphasized',
      identifier: '3f637cec-8c9a-4bb7-bfab-94d9c2ac78f6',
      display: {
        large: {
          font: 'brand',
          weight: 'medium',
          size: 57,
          tracking: 0,
          lineHeight: 64,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 57 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'brand',
          weight: 'medium',
          size: 45,
          tracking: 0,
          lineHeight: 52,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 45 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'brand',
          weight: 'medium',
          size: 36,
          tracking: 0,
          lineHeight: 44,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 36 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      headline: {
        large: {
          font: 'brand',
          weight: 'medium',
          size: 32,
          tracking: 0,
          lineHeight: 40,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 32 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'brand',
          weight: 'medium',
          size: 28,
          tracking: 0,
          lineHeight: 36,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 28 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'brand',
          weight: 'medium',
          size: 24,
          tracking: 0,
          lineHeight: 32,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 24 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      title: {
        large: {
          font: 'brand',
          weight: 'medium',
          size: 22,
          tracking: 0,
          lineHeight: 28,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 22 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'plain',
          weight: 600,
          size: 16,
          tracking: 0,
          lineHeight: 24,
          axes: [
            { name: 'wght', value: 600 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 16 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'plain',
          weight: 600,
          size: 14,
          tracking: 0,
          lineHeight: 20,
          axes: [
            { name: 'wght', value: 600 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 14 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      body: {
        large: {
          font: 'plain',
          weight: 'medium',
          size: 16,
          tracking: 0,
          lineHeight: 24,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 16 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'plain',
          weight: 'medium',
          size: 14,
          tracking: 0,
          lineHeight: 20,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 14 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'plain',
          weight: 'medium',
          size: 12,
          tracking: 0,
          lineHeight: 16,
          axes: [
            { name: 'wght', value: 500 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 12 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
      label: {
        large: {
          font: 'plain',
          weight: 'bold',
          size: 14,
          tracking: 0,
          lineHeight: 20,
          axes: [
            { name: 'wght', value: 600 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 14 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        medium: {
          font: 'plain',
          weight: 'bold',
          size: 12,
          tracking: 0.1,
          lineHeight: 16,
          axes: [
            { name: 'wght', value: 600 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 12 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
        small: {
          font: 'plain',
          weight: 'bold',
          size: 11,
          tracking: 0.1,
          lineHeight: 16,
          axes: [
            { name: 'wght', value: 600 },
            { name: 'GRAD', value: 0 },
            { name: 'wdth', value: 100 },
            { name: 'ROND', value: 0 },
            { name: 'opsz', value: 11 },
            { name: 'CRSV', value: 0 },
            { name: 'slnt', value: 0 },
            { name: 'FILL', value: 0 },
            { name: 'HEXP', value: 0 },
          ],
        },
      },
    },
  ],
  styleSets: {
    button: {
      colors: [
        {
          name: 'elevated',
          identifier: 'ad71a244-76d5-47a6-ad00-a9d0b69f8b03',
          enabled: {
            default: {
              containerColor: 'surface-container-low',
              shadowColor: 'shadow',
              elevation: 1,
              labelColor: 'primary',
              iconColor: 'primary',
            },
            unselected: {
              containerColor: 'surface-container-low',
              labelColor: 'primary',
              iconColor: 'primary',
            },
            selected: {
              containerColor: 'primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
          disabled: {
            default: {
              containerColor: 'on-surface',
              containerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-surface',
              labelOpacity: 0.38,
              iconColor: 'on-surface',
              iconOpacity: 0.38,
            },
          },
          hovered: {
            default: {
              stateLayerColor: 'primary',
              stateLayerOpacity: 0.08,
              labelColor: 'primary',
              iconColor: 'primary',
            },
            unselected: {
              stateLayerColor: 'primary',
              labelColor: 'primary',
              iconColor: 'primary',
            },
            selected: {
              stateLayerColor: 'on-primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
          focused: {
            default: {
              stateLayerColor: 'primary',
              stateLayerOpacity: 0.1,
              elevation: 1,
              labelColor: 'primary',
              iconColor: 'primary',
            },
            unselected: {
              stateLayerColor: 'primary',
              labelColor: 'primary',
              iconColor: 'primary',
            },
            selected: {
              stateLayerColor: 'on-primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
          pressed: {
            default: {
              stateLayerColor: 'primary',
              stateLayerOpacity: 0.1,
              elevation: 1,
              labelColor: 'primary',
              iconColor: 'primary',
            },
            unselected: {
              stateLayerColor: 'primary',
              labelColor: 'primary',
              iconColor: 'primary',
            },
            selected: {
              stateLayerColor: 'on-primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
        },
        {
          name: 'filled',
          identifier: 'c09187e4-d4f2-4be6-93cd-efbf1778d93b',
          enabled: {
            default: {
              containerColor: 'primary',
              shadowColor: 'shadow',
              elevation: 0,
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
            unselected: {
              containerColor: 'surface-container',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              containerColor: 'primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
          disabled: {
            default: {
              containerColor: 'on-surface',
              containerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-surface',
              labelOpacity: 0.38,
              iconColor: 'on-surface',
              iconOpacity: 0.38,
            },
          },
          hovered: {
            default: {
              stateLayerColor: 'on-primary',
              stateLayerOpacity: 0.08,
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
            unselected: {
              stateLayerColor: 'on-surface-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              stateLayerColor: 'on-primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
          focused: {
            default: {
              stateLayerColor: 'on-primary',
              stateLayerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
            unselected: {
              stateLayerColor: 'on-surface-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              stateLayerColor: 'on-primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
          pressed: {
            default: {
              stateLayerColor: 'on-primary',
              stateLayerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
            unselected: {
              stateLayerColor: 'on-surface-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              stateLayerColor: 'on-primary',
              labelColor: 'on-primary',
              iconColor: 'on-primary',
            },
          },
        },
        {
          name: 'tonal',
          identifier: '4153cbaf-2093-4a65-b4ab-fb10b073796d',
          enabled: {
            default: {
              containerColor: 'secondary-container',
              shadowColor: 'shadow',
              elevation: 0,
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            unselected: {
              containerColor: 'secondary-container',
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            selected: {
              containerColor: 'secondary',
              labelColor: 'on-secondary',
              iconColor: 'on-secondary',
            },
          },
          disabled: {
            default: {
              containerColor: 'on-surface',
              containerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-surface',
              labelOpacity: 0.38,
              iconColor: 'on-surface',
              iconOpacity: 0.38,
            },
          },
          hovered: {
            default: {
              stateLayerColor: 'on-secondary-container',
              stateLayerOpacity: 0.08,
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            unselected: {
              stateLayerColor: 'on-secondary-container',
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            selected: {
              stateLayerColor: 'on-secondary',
              labelColor: 'on-secondary',
              iconColor: 'on-secondary',
            },
          },
          focused: {
            default: {
              stateLayerColor: 'on-secondary-container',
              stateLayerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            unselected: {
              stateLayerColor: 'on-secondary-container',
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            selected: {
              stateLayerColor: 'on-secondary',
              labelColor: 'on-secondary',
              iconColor: 'on-secondary',
            },
          },
          pressed: {
            default: {
              stateLayerColor: 'on-secondary-container',
              stateLayerOpacity: 0.1,
              elevation: 0,
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            unselected: {
              stateLayerColor: 'on-secondary-container',
              labelColor: 'on-secondary-container',
              iconColor: 'on-secondary-container',
            },
            selected: {
              stateLayerColor: 'on-secondary',
              labelColor: 'on-secondary',
              iconColor: 'on-secondary',
            },
          },
        },
        {
          name: 'outlined',
          identifier: 'dcf01920-fbf8-46da-a4ca-e7a3353b1ee5',
          enabled: {
            default: {
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            unselected: {
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              containerColor: 'inverse-surface',
              labelColor: 'inverse-on-surface',
              iconColor: 'inverse-on-surface',
            },
          },
          disabled: {
            default: {
              outlineColor: 'outline-variant',
              containerOpacity: 0.1,
              labelColor: 'on-surface',
              labelOpacity: 0.38,
              iconColor: 'on-surface',
              iconOpacity: 0.38,
            },
            unselected: {
              outlineColor: 'outline-variant',
            },
            selected: {
              containerColor: 'on-surface',
            },
          },
          hovered: {
            default: {
              stateLayerColor: 'on-surface-variant',
              stateLayerOpacity: 0.08,
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            unselected: {
              stateLayerColor: 'on-surface-variant',
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              stateLayerColor: 'inverse-on-surface',
              labelColor: 'inverse-on-surface',
              iconColor: 'inverse-on-surface',
            },
          },
          focused: {
            default: {
              stateLayerColor: 'on-surface-variant',
              stateLayerOpacity: 0.1,
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            unselected: {
              stateLayerColor: 'on-surface-variant',
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              stateLayerColor: 'inverse-on-surface',
              labelColor: 'inverse-on-surface',
              iconColor: 'inverse-on-surface',
            },
          },
          pressed: {
            default: {
              stateLayerColor: 'on-surface-variant',
              stateLayerOpacity: 0.1,
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            unselected: {
              stateLayerColor: 'on-surface-variant',
              outlineColor: 'outline-variant',
              labelColor: 'on-surface-variant',
              iconColor: 'on-surface-variant',
            },
            selected: {
              stateLayerColor: 'inverse-on-surface',
              labelColor: 'inverse-on-surface',
              iconColor: 'inverse-on-surface',
            },
          },
        },
        {
          name: 'text',
          identifier: '40c24494-1392-4602-95b2-47b37bcd226b',
          checkable: false,
          enabled: {
            default: {
              labelColor: 'primary',
              iconColor: 'primary',
            },
          },
          disabled: {
            default: {
              containerColor: 'on-surface',
              containerOpacity: 0.1,
              labelColor: 'on-surface',
              labelOpacity: 0.38,
              iconColor: 'on-surface',
              iconOpacity: 0.38,
            },
          },
          hovered: {
            default: {
              stateLayerColor: 'primary',
              stateLayerOpacity: 0.08,
              labelColor: 'primary',
              iconColor: 'primary',
            },
          },
          focused: {
            default: {
              stateLayerColor: 'primary',
              stateLayerOpacity: 0.1,
              labelColor: 'primary',
              iconColor: 'primary',
            },
          },
          pressed: {
            default: {
              stateLayerColor: 'primary',
              stateLayerOpacity: 0.1,
              labelColor: 'primary',
              iconColor: 'primary',
            },
          },
        },
      ],
      sizes: [
        {
          name: 'xsmall',
          identifier: '7754353e-e4ac-4817-a2e8-0a7ebc88f852',
          containerHeight: 32,
          outlineWidth: 1,
          labelSize: {
            font: 'plain',
            weight: 'medium',
            size: 14,
            tracking: 0.1,
            lineHeight: 20,
          },
          iconSize: 20,
          shapeRound: 'full',
          shapeSquare: 'medium',
          leadingSpace: 12,
          betweenIconLabelSpace: 8,
          trailingSpace: 12,
          shapePressedMorph: 'small',
          shapeAnimation: 'fast-spatial',
          selectedContainerShapeRound: 'medium',
          selectedContainerShapeSquare: 'full',
        },
        {
          name: 'small',
          identifier: 'ab3e7e2c-7c26-4677-9304-9877388f0da7',
          containerHeight: 40,
          outlineWidth: 1,
          labelSize: {
            font: 'plain',
            weight: 'medium',
            size: 14,
            tracking: 0.1,
            lineHeight: 20,
          },
          iconSize: 20,
          shapeRound: 'full',
          shapeSquare: 'medium',
          leadingSpace: 16,
          betweenIconLabelSpace: 8,
          trailingSpace: 16,
          shapePressedMorph: 'small',
          shapeAnimation: 'fast-spatial',
          selectedContainerShapeRound: 'medium',
          selectedContainerShapeSquare: 'full',
        },
        {
          name: 'medium',
          identifier: '68b473e4-10fb-49c9-972b-4947bd7a1eac',
          containerHeight: 56,
          outlineWidth: 1,
          labelSize: {
            font: 'plain',
            weight: 'medium',
            size: 16,
            tracking: 0.15,
            lineHeight: 24,
          },
          iconSize: 24,
          shapeRound: 'full',
          shapeSquare: 'large',
          leadingSpace: 24,
          betweenIconLabelSpace: 8,
          trailingSpace: 24,
          shapePressedMorph: 'medium',
          shapeAnimation: 'fast-spatial',
          selectedContainerShapeRound: 'large',
          selectedContainerShapeSquare: 'full',
        },
        {
          name: 'large',
          identifier: '8e704f4e-5538-492b-b505-5141b44633fa',
          containerHeight: 96,
          outlineWidth: 2,
          labelSize: 'headline-small',
          iconSize: 32,
          shapeRound: 'full',
          shapeSquare: 'extra-large',
          leadingSpace: 48,
          betweenIconLabelSpace: 12,
          trailingSpace: 48,
          shapePressedMorph: 'large',
          shapeAnimation: 'fast-spatial',
          selectedContainerShapeRound: 'extra-large',
          selectedContainerShapeSquare: 'full',
        },
        {
          name: 'xlarge',
          identifier: '1f42e807-87a5-45a4-91c1-c63328603701',
          containerHeight: 136,
          outlineWidth: 3,
          labelSize: 'headline-large',
          iconSize: 40,
          shapeRound: 'full',
          shapeSquare: 'extra-large',
          leadingSpace: 64,
          betweenIconLabelSpace: 16,
          trailingSpace: 64,
          shapePressedMorph: 'large',
          shapeAnimation: 'fast-spatial',
          selectedContainerShapeRound: 'extra-large',
          selectedContainerShapeSquare: 'full',
        },
      ],
    },
  },
  components: {
    icon: {
      style: {
        weight: 400,
        fill: false,
        emphasis: false,
        size: 24,
      },
    },
    layout: {
      paneColor: 'surface',
      windowColor: 'surface-container',
    },
    button: {
      checkable: false,
      size: 'small',
      shape: 'round',
      color: 'filled',
    },
    interactive: {
      focusRing: true,
      ripple: true,
      stateLayer: true,
      rippleBehavior: {
        fadeInDuration: '450ms',
        fadeInTimingFunction: 'cubic-bezier(.2, 0, 0, 1)',
        expandDuration: '450ms',
        expandTimingFunction: 'cubic-bezier(.2, 0, 0, 1)',
        fadeOutDuration: '375ms',
        fadeOutTimingFunction: 'linear',
        opacity: 'var(--md-sys-state-pressed-state-layer-opacity)',
      },
      stateLayerBehavior: {
        fadeInDuration: '150ms',
        fadeInTimingFunction: 'linear',
        fadeOutDuration: '150ms',
        fadeOutTimingFunction: 'linear',
        opacity: 'var(--md-sys-state-hover-state-layer-opacity)',
        focusOpacity: 'var(--md-sys-state-focus-state-layer-opacity)',
      },
    },
  },
} satisfies DeepRequired<ModuleOptions>
