import { argbFromHex, themeFromSourceColor, hexFromArgb } from '@material/material-color-utilities'
import { useRuntimeConfig } from '#app'
import { useTheme, useContrast } from '#imports'
import type { ColorTokens } from '../types'

export const useColor = () => {
  const { currentTheme } = useTheme()
  const { currentContrast } = useContrast()
  const materialYu = useRuntimeConfig().public.materialYu
  const theme = themeFromSourceColor(argbFromHex(materialYu.references.color.sourceColor))

  const light: ColorTokens = {
    'primary': hexFromArgb(theme.palettes.primary.tone(40)),
    'on-primary': hexFromArgb(theme.palettes.primary.tone(100)),
    'primary-container': hexFromArgb(theme.palettes.primary.tone(90)),
    'on-primary-container': hexFromArgb(theme.palettes.primary.tone(30)),
    'secondary': hexFromArgb(theme.palettes.secondary.tone(40)),
    'on-secondary': hexFromArgb(theme.palettes.secondary.tone(100)),
    'secondary-container': hexFromArgb(theme.palettes.secondary.tone(90)),
    'on-secondary-container': hexFromArgb(theme.palettes.secondary.tone(30)),
    'tertiary': hexFromArgb(theme.palettes.tertiary.tone(40)),
    'on-tertiary': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'on-tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'error': hexFromArgb(theme.palettes.error.tone(40)),
    'on-error': hexFromArgb(theme.palettes.error.tone(100)),
    'error-container': hexFromArgb(theme.palettes.error.tone(90)),
    'on-error-container': hexFromArgb(theme.palettes.error.tone(30)),
    'surface': hexFromArgb(theme.palettes.neutral.tone(98)),
    'on-surface': hexFromArgb(theme.palettes.neutral.tone(10)),
    'surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(90)),
    'on-surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'surface-container-highest': hexFromArgb(theme.palettes.neutral.tone(90)),
    'surface-container-high': hexFromArgb(theme.palettes.neutral.tone(92)),
    'surface-container': hexFromArgb(theme.palettes.neutral.tone(94)),
    'surface-container-low': hexFromArgb(theme.palettes.neutral.tone(96)),
    'surface-container-lowest': hexFromArgb(theme.palettes.neutral.tone(100)),
    'inverse-surface': hexFromArgb(theme.palettes.neutral.tone(20)),
    'inverse-on-surface': hexFromArgb(theme.palettes.neutral.tone(95)),
    'outline': hexFromArgb(theme.palettes.neutralVariant.tone(50)),
    'outline-variant': hexFromArgb(theme.palettes.neutralVariant.tone(80)),
    'primary-fixed': hexFromArgb(theme.palettes.primary.tone(90)),
    'on-primary-fixed': hexFromArgb(theme.palettes.primary.tone(10)),
    'primary-fixed-dim': hexFromArgb(theme.palettes.primary.tone(80)),
    'on-primary-fixed-variant': hexFromArgb(theme.palettes.primary.tone(30)),
    'inverse-primary': hexFromArgb(theme.palettes.primary.tone(80)),
    'secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(90)),
    'on-secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(10)),
    'secondary-fixed-dim': hexFromArgb(theme.palettes.secondary.tone(80)),
    'on-secondary-fixed-variant': hexFromArgb(theme.palettes.secondary.tone(30)),
    'tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'on-tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(10)),
    'tertiary-fixed-dim': hexFromArgb(theme.palettes.tertiary.tone(80)),
    'on-tertiary-fixed-variant': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'surface-bright': hexFromArgb(theme.palettes.neutral.tone(98)),
    'surface-dim': hexFromArgb(theme.palettes.neutral.tone(87)),
    'scrim': hexFromArgb(theme.palettes.neutral.tone(0)),
    'shadow': hexFromArgb(theme.palettes.neutral.tone(0)),
  }
  const dark: ColorTokens = {
    'primary': hexFromArgb(theme.palettes.primary.tone(80)),
    'on-primary': hexFromArgb(theme.palettes.primary.tone(20)),
    'primary-container': hexFromArgb(theme.palettes.primary.tone(30)),
    'on-primary-container': hexFromArgb(theme.palettes.primary.tone(90)),
    'secondary': hexFromArgb(theme.palettes.secondary.tone(80)),
    'on-secondary': hexFromArgb(theme.palettes.secondary.tone(20)),
    'secondary-container': hexFromArgb(theme.palettes.secondary.tone(30)),
    'on-secondary-container': hexFromArgb(theme.palettes.secondary.tone(90)),
    'tertiary': hexFromArgb(theme.palettes.tertiary.tone(80)),
    'on-tertiary': hexFromArgb(theme.palettes.tertiary.tone(20)),
    'tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'on-tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'error': hexFromArgb(theme.palettes.error.tone(80)),
    'on-error': hexFromArgb(theme.palettes.error.tone(20)),
    'error-container': hexFromArgb(theme.palettes.error.tone(30)),
    'on-error-container': hexFromArgb(theme.palettes.error.tone(90)),
    'surface': hexFromArgb(theme.palettes.neutral.tone(6)),
    'on-surface': hexFromArgb(theme.palettes.neutral.tone(90)),
    'surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'on-surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(80)),
    'surface-container-highest': hexFromArgb(theme.palettes.neutral.tone(22)),
    'surface-container-high': hexFromArgb(theme.palettes.neutral.tone(17)),
    'surface-container': hexFromArgb(theme.palettes.neutral.tone(12)),
    'surface-container-low': hexFromArgb(theme.palettes.neutral.tone(10)),
    'surface-container-lowest': hexFromArgb(theme.palettes.neutral.tone(4)),
    'inverse-surface': hexFromArgb(theme.palettes.neutral.tone(90)),
    'inverse-on-surface': hexFromArgb(theme.palettes.neutral.tone(20)),
    'outline': hexFromArgb(theme.palettes.neutralVariant.tone(60)),
    'outline-variant': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'primary-fixed': hexFromArgb(theme.palettes.primary.tone(90)),
    'on-primary-fixed': hexFromArgb(theme.palettes.primary.tone(10)),
    'primary-fixed-dim': hexFromArgb(theme.palettes.primary.tone(80)),
    'on-primary-fixed-variant': hexFromArgb(theme.palettes.primary.tone(30)),
    'inverse-primary': hexFromArgb(theme.palettes.primary.tone(40)),
    'secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(90)),
    'on-secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(10)),
    'secondary-fixed-dim': hexFromArgb(theme.palettes.secondary.tone(80)),
    'on-secondary-fixed-variant': hexFromArgb(theme.palettes.secondary.tone(30)),
    'tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'on-tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(10)),
    'tertiary-fixed-dim': hexFromArgb(theme.palettes.tertiary.tone(80)),
    'on-tertiary-fixed-variant': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'surface-bright': hexFromArgb(theme.palettes.neutral.tone(24)),
    'surface-dim': hexFromArgb(theme.palettes.neutral.tone(6)),
    'scrim': hexFromArgb(theme.palettes.neutral.tone(0)),
    'shadow': hexFromArgb(theme.palettes.neutral.tone(0)),
  }
  const lightMediumContrast: ColorTokens = {
    'primary': hexFromArgb(theme.palettes.primary.tone(30)),
    'on-primary': hexFromArgb(theme.palettes.primary.tone(100)),
    'primary-container': hexFromArgb(theme.palettes.primary.tone(40)),
    'on-primary-container': hexFromArgb(theme.palettes.primary.tone(100)),
    'secondary': hexFromArgb(theme.palettes.secondary.tone(30)),
    'on-secondary': hexFromArgb(theme.palettes.secondary.tone(100)),
    'secondary-container': hexFromArgb(theme.palettes.secondary.tone(40)),
    'on-secondary-container': hexFromArgb(theme.palettes.secondary.tone(100)),
    'tertiary': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'on-tertiary': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(40)),
    'on-tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'error': hexFromArgb(theme.palettes.error.tone(30)),
    'on-error': hexFromArgb(theme.palettes.error.tone(100)),
    'error-container': hexFromArgb(theme.palettes.error.tone(40)),
    'on-error-container': hexFromArgb(theme.palettes.error.tone(100)),
    'surface': hexFromArgb(theme.palettes.neutral.tone(98)),
    'on-surface': hexFromArgb(theme.palettes.neutral.tone(0)),
    'surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(90)),
    'on-surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(20)),
    'surface-container-highest': hexFromArgb(theme.palettes.neutral.tone(90)),
    'surface-container-high': hexFromArgb(theme.palettes.neutral.tone(92)),
    'surface-container': hexFromArgb(theme.palettes.neutral.tone(94)),
    'surface-container-low': hexFromArgb(theme.palettes.neutral.tone(96)),
    'surface-container-lowest': hexFromArgb(theme.palettes.neutral.tone(100)),
    'inverse-surface': hexFromArgb(theme.palettes.neutral.tone(20)),
    'inverse-on-surface': hexFromArgb(theme.palettes.neutral.tone(100)),
    'outline': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'outline-variant': hexFromArgb(theme.palettes.neutralVariant.tone(50)),
    'primary-fixed': hexFromArgb(theme.palettes.primary.tone(40)),
    'on-primary-fixed': hexFromArgb(theme.palettes.primary.tone(100)),
    'primary-fixed-dim': hexFromArgb(theme.palettes.primary.tone(30)),
    'on-primary-fixed-variant': hexFromArgb(theme.palettes.primary.tone(100)),
    'inverse-primary': hexFromArgb(theme.palettes.primary.tone(80)),
    'secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(40)),
    'on-secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(100)),
    'secondary-fixed-dim': hexFromArgb(theme.palettes.secondary.tone(30)),
    'on-secondary-fixed-variant': hexFromArgb(theme.palettes.secondary.tone(100)),
    'tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(40)),
    'on-tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'tertiary-fixed-dim': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'on-tertiary-fixed-variant': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'surface-bright': hexFromArgb(theme.palettes.neutral.tone(98)),
    'surface-dim': hexFromArgb(theme.palettes.neutral.tone(87)),
    'scrim': hexFromArgb(theme.palettes.neutral.tone(0)),
    'shadow': hexFromArgb(theme.palettes.neutral.tone(0)),
  }
  const darkMediumContrast: ColorTokens = {
    'primary': hexFromArgb(theme.palettes.primary.tone(90)),
    'on-primary': hexFromArgb(theme.palettes.primary.tone(10)),
    'primary-container': hexFromArgb(theme.palettes.primary.tone(60)),
    'on-primary-container': hexFromArgb(theme.palettes.primary.tone(0)),
    'secondary': hexFromArgb(theme.palettes.secondary.tone(90)),
    'on-secondary': hexFromArgb(theme.palettes.secondary.tone(10)),
    'secondary-container': hexFromArgb(theme.palettes.secondary.tone(60)),
    'on-secondary-container': hexFromArgb(theme.palettes.secondary.tone(0)),
    'tertiary': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'on-tertiary': hexFromArgb(theme.palettes.tertiary.tone(10)),
    'tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(60)),
    'on-tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(0)),
    'error': hexFromArgb(theme.palettes.error.tone(90)),
    'on-error': hexFromArgb(theme.palettes.error.tone(10)),
    'error-container': hexFromArgb(theme.palettes.error.tone(60)),
    'on-error-container': hexFromArgb(theme.palettes.error.tone(0)),
    'surface': hexFromArgb(theme.palettes.neutral.tone(6)),
    'on-surface': hexFromArgb(theme.palettes.neutral.tone(100)),
    'surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'on-surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(90)),
    'surface-container-highest': hexFromArgb(theme.palettes.neutral.tone(22)),
    'surface-container-high': hexFromArgb(theme.palettes.neutral.tone(17)),
    'surface-container': hexFromArgb(theme.palettes.neutral.tone(12)),
    'surface-container-low': hexFromArgb(theme.palettes.neutral.tone(10)),
    'surface-container-lowest': hexFromArgb(theme.palettes.neutral.tone(4)),
    'inverse-surface': hexFromArgb(theme.palettes.neutral.tone(90)),
    'inverse-on-surface': hexFromArgb(theme.palettes.neutral.tone(10)),
    'outline': hexFromArgb(theme.palettes.neutralVariant.tone(70)),
    'outline-variant': hexFromArgb(theme.palettes.neutralVariant.tone(60)),
    'primary-fixed': hexFromArgb(theme.palettes.primary.tone(90)),
    'on-primary-fixed': hexFromArgb(theme.palettes.primary.tone(0)),
    'primary-fixed-dim': hexFromArgb(theme.palettes.primary.tone(80)),
    'on-primary-fixed-variant': hexFromArgb(theme.palettes.primary.tone(20)),
    'inverse-primary': hexFromArgb(theme.palettes.primary.tone(30)),
    'secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(90)),
    'on-secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(0)),
    'secondary-fixed-dim': hexFromArgb(theme.palettes.secondary.tone(80)),
    'on-secondary-fixed-variant': hexFromArgb(theme.palettes.secondary.tone(20)),
    'tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'on-tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(0)),
    'tertiary-fixed-dim': hexFromArgb(theme.palettes.tertiary.tone(80)),
    'on-tertiary-fixed-variant': hexFromArgb(theme.palettes.tertiary.tone(20)),
    'surface-bright': hexFromArgb(theme.palettes.neutral.tone(24)),
    'surface-dim': hexFromArgb(theme.palettes.neutral.tone(6)),
    'scrim': hexFromArgb(theme.palettes.neutral.tone(0)),
    'shadow': hexFromArgb(theme.palettes.neutral.tone(0)),
  }
  const lightHighContrast: ColorTokens = {
    'primary': hexFromArgb(theme.palettes.primary.tone(20)),
    'on-primary': hexFromArgb(theme.palettes.primary.tone(100)),
    'primary-container': hexFromArgb(theme.palettes.primary.tone(30)),
    'on-primary-container': hexFromArgb(theme.palettes.primary.tone(100)),
    'secondary': hexFromArgb(theme.palettes.secondary.tone(20)),
    'on-secondary': hexFromArgb(theme.palettes.secondary.tone(100)),
    'secondary-container': hexFromArgb(theme.palettes.secondary.tone(30)),
    'on-secondary-container': hexFromArgb(theme.palettes.secondary.tone(100)),
    'tertiary': hexFromArgb(theme.palettes.tertiary.tone(20)),
    'on-tertiary': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'on-tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'error': hexFromArgb(theme.palettes.error.tone(20)),
    'on-error': hexFromArgb(theme.palettes.error.tone(100)),
    'error-container': hexFromArgb(theme.palettes.error.tone(30)),
    'on-error-container': hexFromArgb(theme.palettes.error.tone(100)),
    'surface': hexFromArgb(theme.palettes.neutral.tone(98)),
    'on-surface': hexFromArgb(theme.palettes.neutral.tone(0)),
    'surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(90)),
    'on-surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(0)),
    'surface-container-highest': hexFromArgb(theme.palettes.neutral.tone(90)),
    'surface-container-high': hexFromArgb(theme.palettes.neutral.tone(92)),
    'surface-container': hexFromArgb(theme.palettes.neutral.tone(94)),
    'surface-container-low': hexFromArgb(theme.palettes.neutral.tone(96)),
    'surface-container-lowest': hexFromArgb(theme.palettes.neutral.tone(100)),
    'inverse-surface': hexFromArgb(theme.palettes.neutral.tone(20)),
    'inverse-on-surface': hexFromArgb(theme.palettes.neutral.tone(100)),
    'outline': hexFromArgb(theme.palettes.neutral.tone(20)),
    'outline-variant': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'primary-fixed': hexFromArgb(theme.palettes.primary.tone(30)),
    'on-primary-fixed': hexFromArgb(theme.palettes.primary.tone(100)),
    'primary-fixed-dim': hexFromArgb(theme.palettes.primary.tone(20)),
    'on-primary-fixed-variant': hexFromArgb(theme.palettes.primary.tone(100)),
    'inverse-primary': hexFromArgb(theme.palettes.primary.tone(80)),
    'secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(30)),
    'on-secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(100)),
    'secondary-fixed-dim': hexFromArgb(theme.palettes.secondary.tone(20)),
    'on-secondary-fixed-variant': hexFromArgb(theme.palettes.secondary.tone(100)),
    'tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(30)),
    'on-tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'tertiary-fixed-dim': hexFromArgb(theme.palettes.tertiary.tone(20)),
    'on-tertiary-fixed-variant': hexFromArgb(theme.palettes.tertiary.tone(100)),
    'surface-bright': hexFromArgb(theme.palettes.neutral.tone(98)),
    'surface-dim': hexFromArgb(theme.palettes.neutral.tone(87)),
    'scrim': hexFromArgb(theme.palettes.neutral.tone(0)),
    'shadow': hexFromArgb(theme.palettes.neutral.tone(0)),
  }
  const darkHighContrast: ColorTokens = {
    'primary': hexFromArgb(theme.palettes.primary.tone(95)),
    'on-primary': hexFromArgb(theme.palettes.primary.tone(0)),
    'primary-container': hexFromArgb(theme.palettes.primary.tone(80)),
    'on-primary-container': hexFromArgb(theme.palettes.primary.tone(0)),
    'secondary': hexFromArgb(theme.palettes.secondary.tone(95)),
    'on-secondary': hexFromArgb(theme.palettes.secondary.tone(0)),
    'secondary-container': hexFromArgb(theme.palettes.secondary.tone(80)),
    'on-secondary-container': hexFromArgb(theme.palettes.secondary.tone(0)),
    'tertiary': hexFromArgb(theme.palettes.tertiary.tone(95)),
    'on-tertiary': hexFromArgb(theme.palettes.tertiary.tone(0)),
    'tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(80)),
    'on-tertiary-container': hexFromArgb(theme.palettes.tertiary.tone(0)),
    'error': hexFromArgb(theme.palettes.error.tone(95)),
    'on-error': hexFromArgb(theme.palettes.error.tone(0)),
    'error-container': hexFromArgb(theme.palettes.error.tone(80)),
    'on-error-container': hexFromArgb(theme.palettes.error.tone(0)),
    'surface': hexFromArgb(theme.palettes.neutral.tone(6)),
    'on-surface': hexFromArgb(theme.palettes.neutral.tone(100)),
    'surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(30)),
    'on-surface-variant': hexFromArgb(theme.palettes.neutralVariant.tone(100)),
    'surface-container-highest': hexFromArgb(theme.palettes.neutral.tone(22)),
    'surface-container-high': hexFromArgb(theme.palettes.neutral.tone(17)),
    'surface-container': hexFromArgb(theme.palettes.neutral.tone(12)),
    'surface-container-low': hexFromArgb(theme.palettes.neutral.tone(10)),
    'surface-container-lowest': hexFromArgb(theme.palettes.neutral.tone(4)),
    'inverse-surface': hexFromArgb(theme.palettes.neutral.tone(90)),
    'inverse-on-surface': hexFromArgb(theme.palettes.neutral.tone(0)),
    'outline': hexFromArgb(theme.palettes.neutral.tone(95)),
    'outline-variant': hexFromArgb(theme.palettes.neutralVariant.tone(80)),
    'primary-fixed': hexFromArgb(theme.palettes.primary.tone(90)),
    'on-primary-fixed': hexFromArgb(theme.palettes.primary.tone(0)),
    'primary-fixed-dim': hexFromArgb(theme.palettes.primary.tone(80)),
    'on-primary-fixed-variant': hexFromArgb(theme.palettes.primary.tone(0)),
    'inverse-primary': hexFromArgb(theme.palettes.primary.tone(20)),
    'secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(90)),
    'on-secondary-fixed': hexFromArgb(theme.palettes.secondary.tone(0)),
    'secondary-fixed-dim': hexFromArgb(theme.palettes.secondary.tone(80)),
    'on-secondary-fixed-variant': hexFromArgb(theme.palettes.secondary.tone(0)),
    'tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(90)),
    'on-tertiary-fixed': hexFromArgb(theme.palettes.tertiary.tone(0)),
    'tertiary-fixed-dim': hexFromArgb(theme.palettes.tertiary.tone(80)),
    'on-tertiary-fixed-variant': hexFromArgb(theme.palettes.tertiary.tone(0)),
    'surface-bright': hexFromArgb(theme.palettes.neutral.tone(24)),
    'surface-dim': hexFromArgb(theme.palettes.neutral.tone(6)),
    'scrim': hexFromArgb(theme.palettes.neutral.tone(0)),
    'shadow': hexFromArgb(theme.palettes.neutral.tone(0)),
  }

  if (currentContrast.value === 'default') {
    if (currentTheme.value === 'light') {
      return light
    }
    else {
      return dark
    }
  }
  else if (currentContrast.value === 'medium') {
    if (currentTheme.value === 'light') {
      return lightMediumContrast
    }
    else {
      return darkMediumContrast
    }
  }
  else {
    if (currentTheme.value === 'light') {
      return lightHighContrast
    }
    else {
      return darkHighContrast
    }
  }
}
